In [1]:
import numpy as np

In [ ]:
array_zeros = np.zeros(10)
print(array_zeros)



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
array_ones = np.ones(10)
print(array_ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
array_ones = np.ones(10)
array_fives = array_ones * 5
print(array_fives)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
array_int=np.arange(10,51)
print(array_int)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [ ]:
array_even=np.arange(10,51,2)
print(array_even)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
arr=np.arange(0,9)
mat=arr.reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
mat_eye=np.eye(3)
print(mat_eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
random_numb=np.random.rand()
print(random_numb)

0.3590405235948876


In [ ]:
random_norm=np.random.randn(25)
print(random_norm)

[-0.70615251 -0.92901551 -1.20539636  0.2836354  -0.01768383 -0.59356328
 -0.92915784  1.16640554  0.50420692 -0.46266256 -0.80585143 -1.37503291
 -0.57981318 -0.26685618  1.43639206  1.57625869  0.39902346 -1.6208356
  1.09745912 -0.88426319  1.38611571  0.38460591 -1.42706908 -1.44786142
 -1.14000705]


In [ ]:
arr=np.arange(0.01,1.01,0.01)
mat=arr.reshape(10,10)
print(mat)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [3]:
mat = np.arange(1,26).reshape(5,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
print(mat[2:5,1:5])

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [4]:
print(mat[3,4])

20


In [6]:
print(mat[0:3,1].reshape(-1,1))

[[ 2]
 [ 7]
 [12]]


In [8]:
print(mat[4])

[21 22 23 24 25]


In [11]:
print(mat[3:5])

[[16 17 18 19 20]
 [21 22 23 24 25]]


In [12]:
print(mat.sum())

325


In [13]:
print(mat.std())

7.211102550927978


In [23]:
print(mat.sum(axis=0))

[55 60 65 70 75]
